// Aeromux Multi-SDR Mode S and ADSB Demodulator and Decoder for .NET
// Copyright (C) 2025-2026 Nandor Toth <dev@nandortoth.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses.

using System.Collections.Concurrent;
using System.Text;
using Aeromux.Core.ModeS;
using Aeromux.Core.ModeS.Enums;
using Aeromux.Core.ModeS.Messages;
using Aeromux.Core.Tracking;

namespace Aeromux.Infrastructure.Network.Protocols;

/// <summary>
/// Encodes parsed ModeSMessage to SBS (BaseStation) CSV format with complete protocol support.
/// SBS format is used by Virtual Radar Server and other ADS-B/Mode S clients.
/// </summary>
/// <remarks>
/// ════════════════════════════════════════════════════════════════════════════════════════════════════
///                             SBS BASESTATION PROTOCOL SPECIFICATION
/// ════════════════════════════════════════════════════════════════════════════════════════════════════
///
/// MESSAGE TYPES
/// ────────────────────────────────────────────────────────────────────────────────────────────────────
/// ┌──────┬────────────────────────────┬─────────────────────────────────────────┐
/// │ Type │ Description                │ Trigger                                 │
/// ├──────┼────────────────────────────┼─────────────────────────────────────────┤
/// │ MSG  │ Transmission Message       │ Generated by aircraft (8 subtypes)      │
/// │ AIR  │ New Aircraft Message       │ SBS picks up new aircraft signal        │
/// │ ID   │ New ID Message             │ Aircraft sets/changes callsign          │
/// │ SEL  │ Selection Change           │ User selects aircraft in BaseStation    │
/// │ CLK  │ Click Message              │ User double-clicks aircraft             │
/// │ STA  │ Status Change              │ Aircraft status timeout changes         │
/// └──────┴────────────────────────────┴─────────────────────────────────────────┘
///
/// MSG SUBTYPES
/// ────────────────────────────────────────────────────────────────────────────────────────────────────
/// ┌───────┬──────────────────────────────┬──────────────────────────────────────┐
/// │ Type  │ Description                  │ Source (DF/TC)                       │
/// ├───────┼──────────────────────────────┼──────────────────────────────────────┤
/// │ MSG,1 │ ES Identification & Category │ DF 17/18, TC 1-4                     │
/// │ MSG,2 │ ES Surface Position          │ DF 17/18, TC 5-8                     │
/// │ MSG,3 │ ES Airborne Position         │ DF 17/18, TC 9-18, 20-22             │
/// │ MSG,4 │ ES Airborne Velocity         │ DF 17/18, TC 19                      │
/// │ MSG,5 │ Surveillance Alt Reply       │ DF 4, 20 (if ES sent previously)     │
/// │ MSG,6 │ Surveillance ID Reply        │ DF 5, 21 (if ES sent previously)     │
/// │ MSG,7 │ Air-to-Air Surveillance      │ DF 0, 16                             │
/// │ MSG,8 │ All-Call Reply               │ DF 11                                │
/// └───────┴──────────────────────────────┴──────────────────────────────────────┘
///
/// FIELD STRUCTURE (22 comma-separated fields)
/// ────────────────────────────────────────────────────────────────────────────────────────────────────
/// ┌────┬─────────────────────┬──────────────────────────────────────────────────┐
/// │ #  │ Field Name          │ Description                                      │
/// ├────┼─────────────────────┼──────────────────────────────────────────────────┤
/// │  1 │ Message Type        │ MSG, AIR, ID, SEL, CLK, STA                      │
/// │  2 │ Transmission Type   │ 1-8 for MSG, empty for others                    │
/// │  3 │ Session ID          │ Database session record number                   │
/// │  4 │ Aircraft ID         │ Database aircraft record number                  │
/// │  5 │ HexIdent            │ 24-bit ICAO address (6 hex digits)               │
/// │  6 │ Flight ID           │ Database flight record number                    │
/// │  7 │ Date Generated      │ YYYY/MM/DD when message was generated            │
/// │  8 │ Time Generated      │ HH:mm:ss.fff when message was generated          │
/// │  9 │ Date Logged         │ YYYY/MM/DD when message was logged (current)     │
/// │ 10 │ Time Logged         │ HH:mm:ss.fff when message was logged (current)   │
/// │ 11 │ Callsign            │ 8-character flight ID or registration            │
/// │ 12 │ Altitude            │ Mode C altitude in feet (Flight Level)           │
/// │ 13 │ GroundSpeed         │ Speed over ground in knots                       │
/// │ 14 │ Track               │ Track angle in degrees (0-360)                   │
/// │ 15 │ Latitude            │ Decimal degrees (North +, South -)               │
/// │ 16 │ Longitude           │ Decimal degrees (East +, West -)                 │
/// │ 17 │ VerticalRate        │ Feet per minute (+ climbing, - descending)       │
/// │ 18 │ Squawk              │ 4-digit octal transponder code                   │
/// │ 19 │ Alert               │ Squawk change flag: -1=true, 0=false, empty=N/A  │
/// │ 20 │ Emergency           │ Emergency flag: -1=true, 0=false, empty=N/A      │
/// │ 21 │ SPI                 │ Ident flag: -1=true, 0=false, empty=N/A          │
/// │ 22 │ IsOnGround          │ Ground flag: -1=true, 0=false                    │
/// └────┴─────────────────────┴──────────────────────────────────────────────────┘
///
/// MESSAGE CONTENT MATRIX (which fields are populated per message type)
/// ────────────────────────────────────────────────────────────────────────────────────────────────────
/// Field:     1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
///          ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┐
/// MSG,1    │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │   │   │   │   │   │   │   │   │   │   │
/// MSG,2    │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │ ● │ ● │ ● │ ● │ ● │   │   │   │   │   │ ● │
/// MSG,3    │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │ ● │   │   │ ● │ ● │   │   │ ● │ ● │ ● │ ● │
/// MSG,4    │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │   │ ● │ ● │   │   │ ● │   │   │   │   │   │
/// MSG,5    │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │ ● │   │   │   │   │   │   │ ● │   │ ● │ ● │
/// MSG,6    │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │ ● │   │   │   │   │   │ ● │ ● │ ● │ ● │ ● │
/// MSG,7    │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │ ● │   │   │   │   │   │   │   │   │   │ ● │
/// MSG,8    │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │   │   │   │   │   │   │   │   │   │   │ ● │
/// AIR      │ ● │   │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │   │   │   │   │   │   │   │   │   │   │   │
/// ID       │ ● │   │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │ ● │   │   │   │   │   │   │   │   │   │   │   │
///          └───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┘
///          ● = Field is populated
///
/// SPECIAL RULES
/// ────────────────────────────────────────────────────────────────────────────────────────────────────
/// - MSG,5 and MSG,6: Only sent if aircraft has previously transmitted MSG,1/2/3/4/8
/// - ID message: Emitted when aircraft first sends callsign (TC 1-4)
/// - AIR message: Emitted when new aircraft is first detected
/// - Line terminator: \r\n (CRLF)
/// - Fields 7-8: Timestamp from Mode S message (when aircraft transmitted)
/// - Fields 9-10: Current timestamp (when SBS line was generated)
/// - Alert/Emergency/SPI/Ground flags: -1 = true, 0 = false, empty = not applicable
///
/// IMPLEMENTATION STATUS
/// ────────────────────────────────────────────────────────────────────────────────────────────────────
/// Complete SBS protocol support with Aircraft State Tracker integration:
/// - MSG,1: ES Aircraft Identification (TC 1-4)
/// - MSG,2: ES Surface Position (TC 5-8)
/// - MSG,3: ES Airborne Position (TC 9-18, 20-22)
/// - MSG,4: ES Airborne Velocity (TC 19)
/// - MSG,5: Surveillance Altitude Reply (DF 4, 20) with ES filtering
/// - MSG,6: Surveillance Identity Reply (DF 5, 21) with ES filtering
/// - MSG,7: Air-to-Air Surveillance (DF 0, 16)
/// - MSG,8: All-Call Reply (DF 11)
/// - AIR: New aircraft detection
/// - ID: Callsign identification
/// - Complete flag support (Alert, Emergency, SPI, IsOnGround)
/// - Dual timestamp handling (message generated vs logged)
/// - Aircraft state correlation across message types
///
/// REFERENCES
/// ────────────────────────────────────────────────────────────────────────────────────────────────────
/// - SBS Protocol: http://woodair.net/SBS/Article/Barebones42_Socket_Data.htm
/// ════════════════════════════════════════════════════════════════════════════════════════════════════
/// </remarks>
public sealed class SbsEncoder : IDisposable
{
    private readonly IAircraftStateTracker _tracker;
    private readonly ConcurrentDictionary<string, AircraftSbsState> _aircraftState;
    private readonly ConcurrentQueue<byte[]> _pendingMessages;

    // Reusable format buffer for UTF-8 output — avoids per-frame byte[] allocations
    // Only used by FormatMsg1-8 (sequential main encode path), not by FormatAir/FormatId (event handlers)
    private byte[] _formatBuffer = new byte[256];

    /// <summary>
    /// Initializes a new instance of the SbsEncoder with Aircraft State Tracker integration.
    /// </summary>
    /// <param name="tracker">Aircraft state tracker for accessing consolidated aircraft data</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="tracker"/> is null</exception>
    public SbsEncoder(IAircraftStateTracker tracker)
    {
        _tracker = tracker ?? throw new ArgumentNullException(nameof(tracker));
        _aircraftState = new ConcurrentDictionary<string, AircraftSbsState>();
        _pendingMessages = new ConcurrentQueue<byte[]>();

        // Subscribe to tracker events
        _tracker.OnAircraftAdded += HandleAircraftAdded;
        _tracker.OnAircraftExpired += HandleAircraftExpired;
    }

    /// <summary>
    /// Encodes a processed frame to SBS format messages.
    /// Returns list of SBS messages (may include AIR, ID, and MSG messages).
    /// </summary>
    /// <param name="frame">Processed frame containing validated frame and parsed message</param>
    /// <returns>List of UTF-8 encoded SBS CSV lines with CRLF terminators</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="frame"/> is null</exception>
    public List<ReadOnlyMemory<byte>> Encode(ProcessedFrame frame)
    {
        ArgumentNullException.ThrowIfNull(frame);

        var messages = new List<ReadOnlyMemory<byte>>();

        // First, dequeue any pending AIR/ID messages from events
        while (_pendingMessages.TryDequeue(out byte[]? pending))
        {
            messages.Add(pending);
        }

        // Skip if message failed to parse
        if (frame.ParsedMessage == null)
        {
            return messages;
        }

        ModeSMessage msg = frame.ParsedMessage;
        string icao = msg.IcaoAddress;
        DateTime msgTime = msg.Timestamp;
        DateTime logTime = DateTime.UtcNow;

        // Get aircraft state from tracker (might be null for some messages)
        Aircraft? aircraft = _tracker.GetAircraft(icao);

        // Get or create SBS state for this aircraft
        AircraftSbsState state = _aircraftState.GetOrAdd(icao, _ => new AircraftSbsState());

        // Encode based on message type
        ReadOnlyMemory<byte>? encoded = msg switch
        {
            AircraftIdentification ident => EncodeIdentification(ident, aircraft, state, msgTime, logTime),
            SurfacePosition surf => EncodeSurfacePosition(surf, aircraft, state, msgTime, logTime),
            AirbornePosition pos => EncodeAirbornePosition(pos, aircraft, state, msgTime, logTime),
            AirborneVelocity vel => EncodeVelocity(vel, aircraft, state, msgTime, logTime),
            SurveillanceAltitudeReply sar => EncodeSurveillanceAlt(sar, aircraft, state, msgTime, logTime),
            SurveillanceIdentityReply sir => EncodeSurveillanceId(sir, aircraft, state, msgTime, logTime),
            AllCallReply acr => EncodeAllCall(acr, aircraft, state, msgTime, logTime),
            LongAirAirSurveillance laas => EncodeAirAirLong(laas, aircraft, msgTime, logTime),
            ShortAirAirSurveillance saas => EncodeAirAirShort(saas, aircraft, msgTime, logTime),
            _ => null
        };

        if (encoded.HasValue)
        {
            messages.Add(encoded.Value);
        }

        return messages;
    }

    /// <summary>
    /// Handles new aircraft detection - emits AIR message.
    /// </summary>
    private void HandleAircraftAdded(object? sender, AircraftEventArgs e)
    {
        // Always emit AIR message for new aircraft
        byte[] airMessage = FormatAirMessage(e.Aircraft.Identification.ICAO, DateTime.UtcNow);
        _pendingMessages.Enqueue(airMessage);
    }

    /// <summary>
    /// Handles aircraft expiration - cleanup state dictionary.
    /// </summary>
    private void HandleAircraftExpired(object? sender, AircraftEventArgs e) =>
        _aircraftState.TryRemove(e.Aircraft.Identification.ICAO, out _);

    /// <summary>
    /// Encodes AircraftIdentification message as MSG,1.
    /// Also emits ID message if this is the first callsign received.
    /// </summary>
    private ReadOnlyMemory<byte> EncodeIdentification(
        AircraftIdentification msg,
        Aircraft? aircraft,
        AircraftSbsState state,
        DateTime msgTime,
        DateTime logTime)
    {
        // Check if we should emit ID message (first time callsign received)
        if (!state.HasSentIdMessage && aircraft?.Identification.Callsign != null)
        {
            byte[] idMessage = FormatIdMessage(
                aircraft.Identification.ICAO,
                aircraft.Identification.Callsign,
                logTime);
            _pendingMessages.Enqueue(idMessage);
            state.HasSentIdMessage = true;
        }

        // Mark that we've sent an ES message (enables MSG,5/6)
        state.HasSentEsMessage = true;

        // Format MSG,1
        return FormatMsg1(msg, aircraft, msgTime, logTime);
    }

    /// <summary>
    /// Encodes SurfacePosition message as MSG,2.
    /// </summary>
    private ReadOnlyMemory<byte> EncodeSurfacePosition(
        SurfacePosition msg,
        Aircraft? aircraft,
        AircraftSbsState state,
        DateTime msgTime,
        DateTime logTime)
    {
        state.HasSentEsMessage = true;
        return FormatMsg2(msg, aircraft, msgTime, logTime);
    }

    /// <summary>
    /// Encodes AirbornePosition message as MSG,3.
    /// </summary>
    private ReadOnlyMemory<byte> EncodeAirbornePosition(
        AirbornePosition msg,
        Aircraft? aircraft,
        AircraftSbsState state,
        DateTime msgTime,
        DateTime logTime)
    {
        state.HasSentEsMessage = true;
        return FormatMsg3(msg, aircraft, msgTime, logTime);
    }

    /// <summary>
    /// Encodes AirborneVelocity message as MSG,4.
    /// </summary>
    private ReadOnlyMemory<byte> EncodeVelocity(
        AirborneVelocity msg,
        Aircraft? aircraft,
        AircraftSbsState state,
        DateTime msgTime,
        DateTime logTime)
    {
        state.HasSentEsMessage = true;
        return FormatMsg4(msg, aircraft, msgTime, logTime);
    }

    /// <summary>
    /// Encodes SurveillanceAltitudeReply message as MSG,5.
    /// Only sent if aircraft has previously sent ES messages (MSG,1/2/3/4/8).
    /// </summary>
    private ReadOnlyMemory<byte>? EncodeSurveillanceAlt(
        SurveillanceAltitudeReply msg,
        Aircraft? aircraft,
        AircraftSbsState state,
        DateTime msgTime,
        DateTime logTime)
    {
        // Filter: MSG,5 only sent if aircraft previously transmitted ES messages
        if (!state.HasSentEsMessage)
        {
            return null;
        }

        return FormatMsg5(msg, aircraft, msgTime, logTime);
    }

    /// <summary>
    /// Encodes SurveillanceIdentityReply message as MSG,6.
    /// Only sent if aircraft has previously sent ES messages (MSG,1/2/3/4/8).
    /// </summary>
    private ReadOnlyMemory<byte>? EncodeSurveillanceId(
        SurveillanceIdentityReply msg,
        Aircraft? aircraft,
        AircraftSbsState state,
        DateTime msgTime,
        DateTime logTime)
    {
        // Filter: MSG,6 only sent if aircraft previously transmitted ES messages
        if (!state.HasSentEsMessage)
        {
            return null;
        }

        return FormatMsg6(msg, aircraft, msgTime, logTime);
    }

    /// <summary>
    /// Encodes AllCallReply message as MSG,8.
    /// </summary>
    private ReadOnlyMemory<byte> EncodeAllCall(
        AllCallReply msg,
        Aircraft? aircraft,
        AircraftSbsState state,
        DateTime msgTime,
        DateTime logTime)
    {
        // Mark as ES message (enables MSG,5/6 per SBS spec)
        state.HasSentEsMessage = true;
        return FormatMsg8(msg, aircraft, msgTime, logTime);
    }

    /// <summary>
    /// Encodes LongAirAirSurveillance message as MSG,7.
    /// </summary>
    private ReadOnlyMemory<byte> EncodeAirAirLong(
        LongAirAirSurveillance msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime) =>
            FormatMsg7(msg, aircraft, msgTime, logTime);

    /// <summary>
    /// Encodes ShortAirAirSurveillance message as MSG,7.
    /// </summary>
    private ReadOnlyMemory<byte> EncodeAirAirShort(
        ShortAirAirSurveillance msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime) =>
            FormatMsg7Short(msg, aircraft, msgTime, logTime);

    // ═══════════════════════════════════════════════════════════════════════════
    // MESSAGE FORMATTERS
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Formats AIR message (new aircraft detected).
    /// Format: AIR,,1,1,{ICAO},1,{Date},{Time},{Date},{Time},,,,,,,,,,,,
    /// </summary>
    private byte[] FormatAirMessage(string icao, DateTime timestamp)
    {
        (string date, string time) = FormatTimestamp(timestamp);
        string line = $"AIR,,1,1,{icao},1,{date},{time},{date},{time},,,,,,,,,,,,";
        return Encoding.UTF8.GetBytes(line + "\r\n");
    }

    /// <summary>
    /// Formats ID message (callsign identification).
    /// Format: ID,,1,1,{ICAO},1,{Date},{Time},{Date},{Time},{Callsign},,,,,,,,,,
    /// </summary>
    private byte[] FormatIdMessage(string icao, string callsign, DateTime timestamp)
    {
        (string date, string time) = FormatTimestamp(timestamp);
        string line = $"ID,,1,1,{icao},1,{date},{time},{date},{time},{callsign},,,,,,,,,,";
        return Encoding.UTF8.GetBytes(line + "\r\n");
    }

    /// <summary>
    /// Formats MSG,1 (ES Aircraft Identification).
    /// Format: MSG,1,1,1,{ICAO},1,{DateGen},{TimeGen},{DateLog},{TimeLog},{Callsign},,,,,,,,,,
    /// </summary>
    private ReadOnlyMemory<byte> FormatMsg1(
        AircraftIdentification msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime)
    {
        (string msgDate, string msgTimeStr) = FormatTimestamp(msgTime);
        (string logDate, string logTimeStr) = FormatTimestamp(logTime);

        // Use callsign from tracker if available, otherwise from message
        string callsign = aircraft?.Identification.Callsign ?? msg.Callsign;

        string line = $"MSG,1,1,1,{msg.IcaoAddress},1,{msgDate},{msgTimeStr},{logDate},{logTimeStr},{callsign},,,,,,,,,,";
        return FormatToMemory(line);
    }

    /// <summary>
    /// Formats MSG,2 (ES Surface Position).
    /// Format: MSG,2,1,1,{ICAO},1,{DateGen},{TimeGen},{DateLog},{TimeLog},,{Alt},{GS},{Track},{Lat},{Lon},,,,,,{Gnd}
    /// </summary>
    private ReadOnlyMemory<byte> FormatMsg2(
        SurfacePosition msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime)
    {
        (string msgDate, string msgTimeStr) = FormatTimestamp(msgTime);
        (string logDate, string logTimeStr) = FormatTimestamp(logTime);

        // Surface position - altitude is always empty
        const string alt = "";

        // Ground speed from message or tracker (already in knots)
        string gs = msg.GroundSpeed?.ToString("F0") ??
                   aircraft?.Velocity.GroundSpeed?.Knots.ToString("F0") ?? "";

        // Track from message or tracker
        string track = msg.GroundTrack?.ToString("F1") ??
                      aircraft?.Velocity.GroundTrack?.ToString("F1") ?? "";

        // Position
        string lat = msg.Position?.Latitude.ToString("F6") ?? "";
        string lon = msg.Position?.Longitude.ToString("F6") ?? "";

        // Always on ground for surface position
        string gnd = "-1";

        string line = $"MSG,2,1,1,{msg.IcaoAddress},1,{msgDate},{msgTimeStr},{logDate},{logTimeStr},,{alt},{gs},{track},{lat},{lon},,,,,,{gnd}";
        return FormatToMemory(line);
    }

    /// <summary>
    /// Formats MSG,3 (ES Airborne Position).
    /// Format: MSG,3,1,1,{ICAO},1,{DateGen},{TimeGen},{DateLog},{TimeLog},,{Alt},,,{Lat},{Lon},,{Alert},{Emer},{SPI},{Gnd}
    /// </summary>
    private ReadOnlyMemory<byte> FormatMsg3(
        AirbornePosition msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime)
    {
        (string msgDate, string msgTimeStr) = FormatTimestamp(msgTime);
        (string logDate, string logTimeStr) = FormatTimestamp(logTime);

        // Altitude from message or tracker
        string alt = msg.Altitude?.Feet.ToString() ??
                    aircraft?.Position.BarometricAltitude?.Feet.ToString() ?? "";

        // Position
        string lat = msg.Position?.Latitude.ToString("F6") ?? "";
        string lon = msg.Position?.Longitude.ToString("F6") ?? "";

        // Extract flags from tracker state
        (string alert, string emergency, string spi, string gnd) =
            ExtractFlags(aircraft?.Identification.FlightStatus,
                        aircraft?.Identification.EmergencyState ?? EmergencyState.NoEmergency,
                        aircraft?.Position.IsOnGround ?? false);

        string line = $"MSG,3,1,1,{msg.IcaoAddress},1,{msgDate},{msgTimeStr},{logDate},{logTimeStr},,{alt},,,{lat},{lon},,{alert},{emergency},{spi},{gnd}";
        return FormatToMemory(line);
    }

    /// <summary>
    /// Formats MSG,4 (ES Airborne Velocity).
    /// Format: MSG,4,1,1,{ICAO},1,{DateGen},{TimeGen},{DateLog},{TimeLog},,,{GS},{Track},,,{VR},,,,,
    /// </summary>
    private ReadOnlyMemory<byte> FormatMsg4(
        AirborneVelocity msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime)
    {
        (string msgDate, string msgTimeStr) = FormatTimestamp(msgTime);
        (string logDate, string logTimeStr) = FormatTimestamp(logTime);

        // Ground speed from message or tracker
        string gs = msg.Velocity?.Knots.ToString("F0") ??
                   aircraft?.Velocity.Speed?.Knots.ToString("F0") ?? "";

        // Track from message or tracker
        string track = msg.Heading?.ToString("F1") ??
                      aircraft?.Velocity.Track?.ToString("F1") ?? "";

        // Vertical rate from message or tracker
        string vrate = msg.VerticalRate?.ToString() ??
                      aircraft?.Velocity.VerticalRate?.ToString() ?? "";

        string line = $"MSG,4,1,1,{msg.IcaoAddress},1,{msgDate},{msgTimeStr},{logDate},{logTimeStr},,,{gs},{track},,,{vrate},,,,,";
        return FormatToMemory(line);
    }

    /// <summary>
    /// Formats MSG,5 (Surveillance Altitude Reply).
    /// Format: MSG,5,1,1,{ICAO},1,{DateGen},{TimeGen},{DateLog},{TimeLog},,{Alt},,,,,,{Alert},,{SPI},{Gnd}
    /// </summary>
    private ReadOnlyMemory<byte> FormatMsg5(
        SurveillanceAltitudeReply msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime)
    {
        (string msgDate, string msgTimeStr) = FormatTimestamp(msgTime);
        (string logDate, string logTimeStr) = FormatTimestamp(logTime);

        // Altitude from message or tracker
        string alt = msg.Altitude?.Feet.ToString() ??
                    aircraft?.Position.BarometricAltitude?.Feet.ToString() ?? "";

        // Extract flags - use FlightStatus from message
        // Note: MSG,5 does NOT include Emergency field per SBS protocol matrix
        (string alert, string _, string spi, string gnd) =
            ExtractFlags(msg.FlightStatus,
                        aircraft?.Identification.EmergencyState ?? EmergencyState.NoEmergency,
                        aircraft?.Position.IsOnGround ?? false);

        string line = $"MSG,5,1,1,{msg.IcaoAddress},1,{msgDate},{msgTimeStr},{logDate},{logTimeStr},,{alt},,,,,,{alert},,{spi},{gnd}";
        return FormatToMemory(line);
    }

    /// <summary>
    /// Formats MSG,6 (Surveillance Identity Reply).
    /// Format: MSG,6,1,1,{ICAO},1,{DateGen},{TimeGen},{DateLog},{TimeLog},,{Alt},,,,,,{Squawk},{Alert},{Emer},{SPI},{Gnd}
    /// </summary>
    private ReadOnlyMemory<byte> FormatMsg6(
        SurveillanceIdentityReply msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime)
    {
        (string msgDate, string msgTimeStr) = FormatTimestamp(msgTime);
        (string logDate, string logTimeStr) = FormatTimestamp(logTime);

        // Altitude from tracker (not in DF 5 message)
        string alt = aircraft?.Position.BarometricAltitude?.Feet.ToString() ?? "";

        // Squawk code from message
        string squawk = msg.SquawkCode;

        // Extract flags - use FlightStatus from message
        (string alert, string emergency, string spi, string gnd) =
            ExtractFlags(msg.FlightStatus,
                        aircraft?.Identification.EmergencyState ?? EmergencyState.NoEmergency,
                        aircraft?.Position.IsOnGround ?? false);

        string line = $"MSG,6,1,1,{msg.IcaoAddress},1,{msgDate},{msgTimeStr},{logDate},{logTimeStr},,{alt},,,,,,{squawk},{alert},{emergency},{spi},{gnd}";
        return FormatToMemory(line);
    }

    /// <summary>
    /// Formats MSG,7 (Air-to-Air Surveillance - Long).
    /// Format: MSG,7,1,1,{ICAO},1,{DateGen},{TimeGen},{DateLog},{TimeLog},,{Alt},,,,,,,,,,{Gnd}
    /// </summary>
    private ReadOnlyMemory<byte> FormatMsg7(
        LongAirAirSurveillance msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime)
    {
        (string msgDate, string msgTimeStr) = FormatTimestamp(msgTime);
        (string logDate, string logTimeStr) = FormatTimestamp(logTime);

        // Altitude from message or tracker
        string alt = msg.Altitude?.Feet.ToString() ??
                    aircraft?.Position.BarometricAltitude?.Feet.ToString() ?? "";

        // Ground flag from tracker
        string gnd = aircraft?.Position.IsOnGround == true ? "-1" : "0";

        string line = $"MSG,7,1,1,{msg.IcaoAddress},1,{msgDate},{msgTimeStr},{logDate},{logTimeStr},,{alt},,,,,,,,,,{gnd}";
        return FormatToMemory(line);
    }

    /// <summary>
    /// Formats MSG,7 (Air-to-Air Surveillance - Short).
    /// Format: MSG,7,1,1,{ICAO},1,{DateGen},{TimeGen},{DateLog},{TimeLog},,{Alt},,,,,,,,,,{Gnd}
    /// </summary>
    private ReadOnlyMemory<byte> FormatMsg7Short(
        ShortAirAirSurveillance msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime)
    {
        (string msgDate, string msgTimeStr) = FormatTimestamp(msgTime);
        (string logDate, string logTimeStr) = FormatTimestamp(logTime);

        // Altitude from message or tracker
        string alt = msg.Altitude?.Feet.ToString() ??
                    aircraft?.Position.BarometricAltitude?.Feet.ToString() ?? "";

        // Ground flag from tracker
        string gnd = aircraft?.Position.IsOnGround == true ? "-1" : "0";

        string line = $"MSG,7,1,1,{msg.IcaoAddress},1,{msgDate},{msgTimeStr},{logDate},{logTimeStr},,{alt},,,,,,,,,,{gnd}";
        return FormatToMemory(line);
    }

    /// <summary>
    /// Formats MSG,8 (All-Call Reply).
    /// Format: MSG,8,1,1,{ICAO},1,{DateGen},{TimeGen},{DateLog},{TimeLog},,,,,,,,,,,,{Gnd}
    /// </summary>
    private ReadOnlyMemory<byte> FormatMsg8(
        AllCallReply msg,
        Aircraft? aircraft,
        DateTime msgTime,
        DateTime logTime)
    {
        (string msgDate, string msgTimeStr) = FormatTimestamp(msgTime);
        (string logDate, string logTimeStr) = FormatTimestamp(logTime);

        // Ground flag from tracker
        string gnd = aircraft?.Position.IsOnGround == true ? "-1" : "0";

        string line = $"MSG,8,1,1,{msg.IcaoAddress},1,{msgDate},{msgTimeStr},{logDate},{logTimeStr},,,,,,,,,,,,{gnd}";
        return FormatToMemory(line);
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // HELPER METHODS
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Encodes a CSV line into the reusable format buffer with CRLF terminator.
    /// Returns a memory slice of the internal buffer — valid until the next call.
    /// </summary>
    /// <param name="line">SBS CSV line without terminator</param>
    /// <returns>UTF-8 encoded line with CRLF as a memory slice of the reusable buffer</returns>
    private ReadOnlyMemory<byte> FormatToMemory(string line)
    {
        int byteCount = Encoding.UTF8.GetByteCount(line) + 2; // +\r\n
        if (byteCount > _formatBuffer.Length)
        {
            _formatBuffer = new byte[byteCount * 2];
        }

        int written = Encoding.UTF8.GetBytes(line, _formatBuffer);
        _formatBuffer[written] = (byte)'\r';
        _formatBuffer[written + 1] = (byte)'\n';
        return _formatBuffer.AsMemory(0, written + 2);
    }

    /// <summary>
    /// Formats DateTime as SBS date and time strings.
    /// </summary>
    /// <returns>Tuple of (date: "YYYY/MM/DD", time: "HH:mm:ss.fff")</returns>
    private static (string date, string time) FormatTimestamp(DateTime timestamp)
    {
        string date = timestamp.ToString("yyyy/MM/dd");
        string time = timestamp.ToString("HH:mm:ss.fff");
        return (date, time);
    }

    /// <summary>
    /// Extracts SBS flags from FlightStatus, EmergencyState, and IsOnGround.
    /// Converts Mode-S enumeration values to SBS protocol flag format.
    /// </summary>
    /// <param name="flightStatus">Flight status from Mode-S surveillance reply (may be null)</param>
    /// <param name="emergencyState">Emergency state from aircraft status or tracker</param>
    /// <param name="isOnGround">True if aircraft is on ground, false if airborne</param>
    /// <returns>Tuple of (alert, emergency, spi, isOnGround) as SBS flag strings (-1/0/empty)</returns>
    private static (string alert, string emergency, string spi, string isOnGround) ExtractFlags(
        FlightStatus? flightStatus,
        EmergencyState emergencyState,
        bool isOnGround)
    {
        // Alert flag: -1 = alert active, 0 = no alert, empty = N/A
        string alert = flightStatus switch
        {
            FlightStatus.AirborneAlert or FlightStatus.OnGroundAlert or FlightStatus.AlertSPI => "-1",
            FlightStatus.AirborneNormal or FlightStatus.OnGroundNormal or FlightStatus.NoAlertSPI => "0",
            _ => ""
        };

        // Emergency flag: -1 = emergency active, 0 = no emergency
        string emergency = emergencyState switch
        {
            EmergencyState.GeneralEmergency or EmergencyState.LifeguardMedical or EmergencyState.MinimumFuel or
            EmergencyState.NoCommunications or EmergencyState.UnlawfulInterference or EmergencyState.DownedAircraft => "-1",
            EmergencyState.NoEmergency => "0",
            _ => ""
        };

        // SPI (ident) flag: -1 = SPI active, 0 = not active, empty = N/A
        string spi = flightStatus switch
        {
            FlightStatus.AlertSPI or FlightStatus.NoAlertSPI => "-1",
            FlightStatus.AirborneNormal or FlightStatus.OnGroundNormal or
            FlightStatus.AirborneAlert or FlightStatus.OnGroundAlert => "0",
            _ => ""
        };

        // IsOnGround flag: -1 = on ground, 0 = airborne
        string gnd = isOnGround ? "-1" : "0";

        return (alert, emergency, spi, gnd);
    }

    /// <summary>
    /// Disposes resources and unsubscribes from tracker events.
    /// </summary>
    public void Dispose()
    {
        _tracker.OnAircraftAdded -= HandleAircraftAdded;
        _tracker.OnAircraftExpired -= HandleAircraftExpired;
    }
}

/// <summary>
/// Per-aircraft state for SBS encoding.
/// Tracks which message types have been sent to support SBS protocol filtering rules.
/// </summary>
internal sealed class AircraftSbsState
{
    /// <summary>
    /// True if aircraft has sent Extended Squitter messages (MSG,1/2/3/4/8).
    /// Required to be true before MSG,5 and MSG,6 can be sent per SBS specification.
    /// </summary>
    public bool HasSentEsMessage { get; set; }

    /// <summary>
    /// True if ID message has been sent for this aircraft.
    /// Ensures ID message is only sent once when callsign first becomes available.
    /// </summary>
    public bool HasSentIdMessage { get; set; }
}
